export const prompts = [
  "A group of explorers encountering a lost civilization in the Arctic.",
  "A mystical forest where trees sing with the wind.",
  "A post-apocalyptic wasteland with remnants of a destroyed civilization.",
  "A cybernetic desert where sandstorms reveal buried secrets.",
  "A hidden village hidden behind a waterfall.",
  "A group of adventurers discovering a hidden island filled with ancient ruins.",
  "A steampunk cityscape with towering clock towers and brass dirigibles.",
  "A magical library filled with ancient tomes and scrolls.",
  "A futuristic cityscape with flying cars and holographic advertisements.",
  "A group of explorers encountering a lost tribe deep in the Amazon rainforest.",
  "A haunted castle shrouded in mist with ghostly figures wandering the halls.",
  "A cybernetic wasteland where scavengers hunt for spare parts.",
  "A hidden temple hidden beneath the waves.",
  "A post-apocalyptic world where survivors eke out a living in the ruins of civilization.",
  "A fantastical city suspended in the clouds with bridges connecting towering spires.",
  "A group of adventurers exploring an ancient pyramid filled with traps.",
  "A cybernetic cityscape where humans and machines live together in harmony.",
  "A haunted forest where the trees whisper secrets to those who dare to listen.",
  "A futuristic cityscape with towering skyscrapers and flying vehicles.",
  "A hidden valley inhabited by a reclusive tribe.",
  "A group of pirates sailing on a ship made of living wood.",
  "A mystical temple hidden deep within a dense jungle.",
  "A post-apocalyptic wasteland where mutants roam freely.",
  "A cybernetic wasteland where technology and nature clash.",
  "A hidden village hidden within a labyrinth of caves.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a waterfall.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the Sahara.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
  "A post-apocalyptic world where survivors battle for control of dwindling resources.",
  "A fantastical cityscape with buildings made of crystal and gold.",
  "A group of adventurers exploring an ancient tomb filled with traps.",
  "A cybernetic cityscape where humans and robots coexist uneasily.",
  "A haunted forest where strange creatures lurk in the shadows.",
  "A futuristic cityscape with towering skyscrapers and flying cars.",
  "A hidden valley inhabited by a tribe of peaceful giants.",
  "A group of pirates sailing on a ship made of living ice.",
  "A mystical temple hidden deep within a dense rainforest.",
  "A post-apocalyptic wasteland where survivors scavenge for scraps.",
  "A cybernetic wasteland where machines wage war on each other.",
  "A hidden village hidden within a network of underground tunnels.",
  "A group of explorers discovering a lost city hidden in the mountains.",
  "A steampunk cityscape with towering smokestacks and brass gears.",
  "A magical garden hidden behind a curtain of water.",
  "A futuristic cityscape with flying cars and towering skyscrapers.",
  "A group of adventurers encountering a lost civilization in the heart of the jungle.",
  "A haunted mansion shrouded in mist with ghostly figures appearing in the windows.",
  "A cybernetic wasteland where machines roam unchecked.",
  "A hidden temple hidden within a volcano.",
];
